---
- name: Play to renew Vault management token
  hosts: localhost

  pre_tasks:

    - name: Assert that required variables are present
      ansible.builtin.assert:
        that:
          - vault_address is defined
          - vault_token is defined

  tasks:

    - name: Renew Vault management token
      ansible.builtin.uri:
        url: "{{ vault_address }}/v1/auth/token/renew-self"
        method: POST
        headers:
          X-Vault-Token: "{{ vault_token }}"
